#!/usr/bin/env node
/**
 * Keeps components from reaching around LEDGER — see docs/design/LEDGER.md.
 *
 * The product's entire visual system is `app/design/ledger.css`: every
 * colour, type size, radius and shadow the product uses is declared there,
 * wired into Tailwind's theme layer, and consumed everywhere else as a
 * Tailwind utility class (`bg-canvas`, `text-ink-2`, `rounded-card`, ...).
 * No CSS-in-JS runtime, no arbitrary `style={{ color: "#hex" }}`. That
 * arrangement is only true for as long as no file hardcodes a value the
 * token layer cannot reach, or references a custom property nothing
 * declares — and this script is what makes both mechanical rather than a
 * matter of discipline.
 *
 * WHY THAT MATTERS. A stray hex is a value in the wrong file — annoying,
 * findable, fixable by moving it. A `var(--gray-a5)` reference to a name
 * NOTHING declares is worse: it type-checks, it builds, it renders — as
 * nothing, silently, because an undefined custom property simply resolves
 * to the property's initial value. That is exactly how ~40 dead token
 * references shipped in a previous design-system removal, all invisible
 * until someone looked at the rendered page. Every rule below that bans a
 * hardcoded value would have passed every one of those lines; only a rule
 * that checks a referenced name against the set of names that actually
 * exist catches this class of bug, so that is what the EXISTENCE rule at
 * the bottom of this file does.
 *
 * THIS SCRIPT USED TO ALSO POLICE A SECOND, closed class vocabulary
 * (INSTRUMENT's hand-written `i-*` component classes and a small `v1-*`/
 * `tnum` family, checked against a generated stylesheet). That system —
 * components/ds, components/ui, app/design/tokens.css,
 * app/design/system.generated.css and the generator that built it — was
 * decommissioned once every screen finished migrating to Ledger (see
 * docs/design/LEDGER.md's migration table, phase 6). Ledger has no
 * equivalent closed vocabulary to check a className string against:
 * `bg-canvas`, `rounded-card` and every other Ledger utility are ordinary
 * Tailwind classes, generated by Tailwind's own JIT scan of the source —
 * there is no hand-maintained "list of real classes" file for this script
 * to diff a literal string against the way system.generated.css was one.
 * A typo'd Tailwind utility is a different, and differently-solved,
 * problem (Tailwind IntelliSense / a Tailwind-aware lint rule), out of
 * scope for this script.
 *
 * Scans app/, components/ and lib/ for:
 *   - hex colours at any valid length (3/4/6/8 digit)
 *   - rgb()/rgba()/hsl()/hsla(), and oklch()/oklab()/lab()/lch()/hwb()/
 *     color-mix()/color()
 *   - bare named CSS colours on colour-bearing properties (a heuristic,
 *     not the full 150-name list)
 *   - non-zero border-radius, any font-family, non-token box-shadow and
 *     backdrop-filter — matched across the whole file so a value wrapped
 *     onto its own line cannot hide from a per-line scanner
 *   - JSX inline `style={{...}}` objects: a camelCase visual property
 *     (borderRadius, fontFamily, ...) carrying a literal rather than a
 *     var(--...) reference. Plain `style={{ borderRight: "1px solid
 *     var(--edge)" }}` is a legitimate escape hatch for the cases Tailwind
 *     utilities don't cover and is not banned outright.
 *   - `@mui/*` and `@emotion/*` imports — never part of this product
 *   - the literal brand strings "V1" / "AMG" outside lib/brand.ts
 *   - `@radix-ui/themes` imports anywhere. The package is uninstalled;
 *     this rule is a regression fence, not a live constraint.
 *   - EXISTENCE: any `var(--x)` whose name nothing declares. See "THE
 *     EXISTENCE RULE" below.
 *
 * The files allowed to spell a value out are listed at EXEMPT_FILES below,
 * each with the reason it earns the exemption. That exemption is scoped to
 * the VALUE rules only (hex/color-function/named-color/radius/font-family/
 * box-shadow/backdrop-filter/inline-style-literal) — it does NOT extend to
 * the import-ban rules or the existence rule. See the note above
 * EXEMPT_FILES for why that distinction matters.
 *
 * REWRITE NOTE, retained because it is still the reason several of these
 * patterns look the way they do: an adversarial review of an early version
 * of this script found it caught almost nothing beyond bare same-line hex —
 * inline style objects, every modern colour function, named colours,
 * 4-digit hex, and any declaration whose value wrapped onto a second line
 * all passed silently, and lib/ was never scanned despite being listed.
 * The current patterns were built by probing the script empirically, not by
 * reading it. Probe any new rule the same way; see the note above the
 * border-radius rule for a lookahead that reads correct and is not.
 *
 * Line and block comments are stripped before scanning, so this file's own
 * prose about hex codes and brand strings does not trip the checks. That
 * is a textual heuristic, not a parser — a `//` inside a string literal
 * can be mis-stripped, a tradeoff that favours fewer false positives.
 *
 * Run: npm run tokens:verify
 */
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, extname, relative } from "node:path";

const ROOT = process.cwd();
const SCAN_DIRS = ["app", "components", "lib"];

/**
 * Only these files may spell a visual value out:
 *
 *   app/design/ledger.css  THE token layer. Every colour, length, radius
 *                       and shadow in the product is declared here and
 *                       nowhere else — exempt for the same reason a
 *                       dictionary is exempt from a spell-checker. That
 *                       exemption is what makes the rule enforceable
 *                       everywhere ELSE: there is now a correct place to
 *                       put a value, so "move it to ledger.css" is always
 *                       an available answer. ledger.css wipes Tailwind's
 *                       stock palette (`--color-*: initial`), so a
 *                       non-Ledger color utility has no definition to
 *                       resolve to and visibly fails instead of silently
 *                       shipping.
 *   app/globals.css    The V1 mark's brand-identity constants (a plain SVG
 *                       component, not part of any design system) plus
 *                       one touch-device font-sizing rule.
 *   lib/brand.ts        the two theme-color literals, which Next's
 *                       metadata layer cannot read from CSS.
 *   lib/pdf-palette.ts  the bridge to the invoice PDF. @react-pdf/renderer
 *                       has its own styling engine and cannot read CSS, so
 *                       it reaches the same palette through
 *                       @radix-ui/colors instead. Read that file's header
 *                       before adding anything to it.
 *   lib/invoice-pdf.tsx the PDF document itself. Same reason, one step
 *                       further: react-pdf's StyleSheet.create() is not
 *                       CSS and not a JSX style prop — it cannot take a
 *                       var() reference at all, so `fontSize: 10` is the
 *                       only thing that can be written there. Its COLOURS
 *                       still come from pdf-palette, which is the part
 *                       that actually matters; sizes and weights are
 *                       necessarily literal in a PDF.
 *   lib/pilot-history-pdf.tsx, lib/estimate-pdf.tsx,
 *   lib/reimbursables-packet-pdf.tsx
 *                       the other react-pdf documents. Identical reasoning
 *                       to lib/invoice-pdf.tsx, and each is LISTED rather
 *                       than the exemption being widened to a
 *                       `lib/*-pdf.tsx` glob: a pattern would silently
 *                       exempt the next file somebody happens to name that
 *                       way, which is exactly the drift this list exists
 *                       to keep deliberate. Colours come from pdf-palette
 *                       too; only StyleSheet.create()'s sizes and weights
 *                       need the exemption.
 */
const EXEMPT_FILES = new Set([
  join(ROOT, "app", "design", "ledger.css"),
  join(ROOT, "app", "globals.css"),
  join(ROOT, "lib", "brand.ts"),
  join(ROOT, "lib", "pdf-palette.ts"),
  join(ROOT, "lib", "invoice-pdf.tsx"),
  join(ROOT, "lib", "pilot-history-pdf.tsx"),
  join(ROOT, "lib", "estimate-pdf.tsx"),
  join(ROOT, "lib", "reimbursables-packet-pdf.tsx"),
  // Same class of exemption as the PDF renderers above, for the same
  // reason: this file's GET handler returns a hand-built HTML string
  // (an interstitial that has to survive a mail-scanner GET without
  // spending a one-time auth token — see its own header comment), not a
  // React tree Next's page pipeline renders. A Route Handler response
  // never reaches app/design/ledger.css's compiled, hashed stylesheet, so
  // there is no Tailwind utility or var(--...) token for it to use.
  join(ROOT, "app", "auth", "confirm", "route.ts"),
]);
const EXEMPT_DIRS = [];

// EXEMPT_FILES/isExempt() below governs the VALUE rules only (category
// "value" on RULES) — hex, color functions, named colors, radius,
// font-family, box-shadow, backdrop-filter, inline-style literals. It
// must NEVER be consulted for the import-ban rules (category
// "import-ban") or the existence rule (category "existence") — isExempt()
// used to be checked before ANY rule ran, which meant app/globals.css,
// lib/brand.ts, lib/pdf-palette.ts and lib/invoice-pdf.tsx were silently
// exempt from the @radix-ui/themes import ban too. lib/invoice-pdf.tsx is a
// real .tsx component file — the one place in the exemption list a Radix
// component could actually be imported directly with no signal anywhere
// that it happened. scanFile() below now applies EXEMPT_FILES only to
// rules whose category is "value"; import-ban and existence rules run on
// every scanned file regardless of EXEMPT_FILES, with only the narrower,
// explicit carve-outs named where each rule is defined.
//
// Verified by temporarily adding `import { Card } from "@radix-ui/themes";`
// to lib/invoice-pdf.tsx and confirming `node scripts/verify-tokens.mjs`
// failed on it, then reverting.

// @radix-ui/themes is uninstalled — no file in this product needs to
// import it any more. So the "radix-themes-import" rule below carries no
// exemption: if a future migration genuinely needs a carve-out again,
// that is a decision to make deliberately when it happens, not a dead
// allow-list left lying around for something to fall into unnoticed.

/*
 * ---------------------------------------------------------------------------
 * THE SLOT-ORIGIN RULES (category "slot-origin").
 *
 * Everything above this point polices values a DEVELOPER writes. A tenant
 * theme adds a second, sharper problem: a visual value that arrives at
 * render time, from a database row, and therefore from outside every rule
 * above — none of which can see a string that is not in the source.
 *
 * The answer is not to police the value (there is nothing to grep) but to
 * police the ORIGIN. lib/theme-slots.ts enumerates every overridable
 * visual value as a closed list (accent / density / appearance names) and
 * resolves an untrusted blob against it with a total function. If that
 * file is the only place such a value can come from, and the only places
 * it can be APPLIED are the two files that render a resolved slot, then no
 * other file in the product can inject one — which is the same guarantee
 * the rules above give for hardcoded values, extended to values that do
 * not exist until runtime.
 *
 * Two constructions carry that risk and both are banned outside their one
 * permitted home:
 *
 *   runtime-css-var     `var(--${x})` — a custom property NAME assembled
 *                       at runtime. This is the construction that turns an
 *                       arbitrary string into a token reference, and it is
 *                       how a free-text colour would eventually be smuggled
 *                       into a style. Only lib/theme-slots.ts may write it.
 *   dynamic-theme-prop  a data-appearance/data-accent/data-density value
 *                       (or object spread) applied from a JSX expression.
 *                       Everywhere except the app shell and the appearance
 *                       panel's live preview, a tenant theme attribute must
 *                       come from a literal, so no third file can start
 *                       theming anything from data.
 *
 * NOTE WHAT IS NOT DONE HERE. lib/theme-slots.ts is deliberately NOT added
 * to EXEMPT_FILES. The hex ban must keep applying to it above all — "a
 * curated palette of enumerated slots, never a free hex" is the promise
 * that file exists to make, and exempting it from the hex rule would be
 * exempting it from its own contract. It needs no value exemption anyway:
 * its swatches are var() references to the token layer's own scales, not
 * colours.
 * ---------------------------------------------------------------------------
 */
const SLOT_ORIGIN_FILE = join(ROOT, "lib", "theme-slots.ts");
const THEME_APPLIER_FILES = new Set([
  // The app shell: stamps the tenant's resolved slots as data attributes.
  join(ROOT, "app", "(app)", "app-shell.tsx"),
  // The appearance panel's preview card, which shows a pilot the accent
  // they are about to save before they save it. Same values, same
  // enumerated source, one screen.
  join(ROOT, "app", "(app)", "settings", "appearance-panel.tsx"),
]);
// .js/.jsx included alongside .ts/.tsx/.css: Next.js compiles .jsx and
// .js in app/ exactly the same as .tsx, so an import or a hardcoded
// value written in one of those files would otherwise be invisible to
// this scanner. Only app/, components/ and lib/ are scanned (SCAN_DIRS
// above) and walk() already skips node_modules and .next, so widening
// the extension set does not risk scanning build output or dependencies
// — there is no .js/.jsx under those three directories today.
const SCAN_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".css"]);

function isExempt(file) {
  if (EXEMPT_FILES.has(file)) return true;
  return EXEMPT_DIRS.some((dir) => file.startsWith(dir + "/"));
}

const NAMED_COLOR_ALLOWLIST = new Set([
  "inherit", "currentcolor", "transparent", "initial", "unset", "none", "inset",
]);

/**
 * Each rule: { id, category, name, pattern, appliesTo: 'css' | 'code' | 'both' }.
 * `id` is the stable key scanFile() uses to special-case a rule — NEVER
 * `name`. `name` is prose meant to read well in the failure output and is
 * expected to change; keying behaviour off it means editing an error
 * message for clarity silently changes which file is exempt from what.
 * `category` is "value" (governed by EXEMPT_FILES), "import-ban" or
 * "slot-origin" (never governed by EXEMPT_FILES — see the note above
 * EXEMPT_FILES for why). Patterns run against the WHOLE file (not per
 * line) with the `g` flag so a value split across lines is still caught,
 * and every match is reported (matchAll), not just the first per pattern.
 */
const RULES = [
  {
    id: "hex-color",
    category: "value",
    name: "hardcoded hex color",
    appliesTo: "both",
    pattern: /#[0-9a-fA-F]{3,8}\b/g,
  },
  {
    id: "color-function",
    category: "value",
    name: "hardcoded color function (rgb/hsl/oklch/lab/color-mix/...)",
    appliesTo: "both",
    pattern: /\b(?:rgba?|hsla?|oklch|oklab|lab|lch|hwb|color-mix|color)\s*\(/g,
  },
  {
    id: "named-color",
    category: "value",
    name: "bare named color on a color-bearing CSS property",
    appliesTo: "both",
    pattern:
      /\b(?:color|background-color|border-color|fill|stroke)\s*:\s*([a-zA-Z]+)\s*;/g,
    filter: (match) => !NAMED_COLOR_ALLOWLIST.has(match[1].toLowerCase()),
  },
  /*
   * A NOTE ON THE SHAPE OF THE FOUR RULES BELOW.
   *
   * Each means "this property must resolve through a token", so each needs
   * a negative lookahead for `var(`. The obvious spelling —
   *
   *     /border-radius\s*:\s*(?!var\()[^;]*;/
   *
   * — is broken. `\s*` is greedy but it BACKTRACKS: when the lookahead
   * fails at the position after the space, the engine retries with `\s*`
   * matching zero characters, which slides the lookahead onto the SPACE
   * rather than onto `var`, where `(?!var\()` trivially succeeds. The guard
   * then guards nothing, and `border-radius: var(--radius);` — the correct
   * form — is reported as a violation.
   *
   * The fix is to pull the whitespace inside the lookahead, leaving no
   * separate quantifier to backtrack over:
   *
   *     /border-radius\s*:(?!\s*var\()[^;]*;/
   *
   * Found by probing this script against a file of known-good and
   * known-bad declarations, not by reading it. Probe any future rule of
   * this shape the same way — the failure is invisible on inspection.
   */
  {
    id: "border-radius",
    category: "value",
    name: "non-token border-radius",
    appliesTo: "css",
    // [^;]* rather than [^\n;]* so a value wrapped onto its own line is
    // still matched: a negated character class matches newlines.
    pattern: /border-radius\s*:(?!\s*(?:0\b|var\())[^;]*;/g,
  },
  {
    id: "font-family",
    category: "value",
    name: "font-family outside the token file",
    appliesTo: "css",
    pattern: /font-family\s*:(?!\s*var\()[^;]*;/g,
  },
  {
    // Ledger has real elevation and real blur (--shadow-card, --shadow-raised).
    // "A surface may take exactly one shadow" and "do not add a second" are
    // only enforceable if every shadow resolves through the token layer.
    id: "box-shadow",
    category: "value",
    name: "non-token box-shadow (must resolve through a --shadow-* var)",
    appliesTo: "css",
    // The var() lookahead spans the whole declaration rather than just its
    // head: a legitimate shadow can be tokens composed on one line, so
    // requiring var() immediately after the colon would reject that idiom.
    pattern: /box-shadow\s*:(?!\s*none\b)(?![^;]*var\()[^;]*;/g,
  },
  {
    id: "backdrop-filter",
    category: "value",
    name: "non-token backdrop-filter",
    appliesTo: "css",
    pattern: /backdrop-filter\s*:(?!\s*(?:none\b|var\())[^;]*;/g,
  },
  {
    // Inline style objects are NOT banned outright. The token layer is
    // reached through CSS custom properties, and Ledger's primitives
    // deliberately do not give every surface a prop for every declaration,
    // so `style={{ borderRight: "1px solid var(--edge)" }}` is a
    // legitimate idiom for the cases Tailwind utilities don't cover.
    // Banning it outright would push people toward worse workarounds.
    //
    // What is still banned is a camelCase visual property carrying a
    // LITERAL — `borderRadius: 6`, `fontFamily: "Inter"` — because those
    // are JS object keys that no CSS-syntax regex will ever see, which is
    // exactly where hardcoded values hide. Requiring var() on this short
    // list keeps the escape hatch open and the token layer authoritative.
    // THE WHITESPACE IS INSIDE THE LOOKAHEAD, and it has to be. Written
    // as `\s*:\s*(?!["'`]?\s*var\()`, the trailing `\s*` is greedy and
    // BACKTRACKS: when the lookahead correctly fails against `"var(`, the
    // engine retries with `\s*` matching zero characters, which slides the
    // lookahead onto the SPACE, where `var\(` cannot match and the negative
    // lookahead trivially succeeds. Every correct `borderRadius:
    // "var(--radius)"` was reported as a violation.
    //
    // This is the second rule in this file to hit that trap; the note above
    // the border-radius rule describes the first. Both were found by
    // running the script, not by reading it. Probe the next one too.
    id: "inline-style-literal",
    category: "value",
    name: "camelCase style property with a literal value (must use var(--…))",
    appliesTo: "code",
    pattern:
      /\b(?:borderRadius|fontFamily|fontSize|fontWeight|letterSpacing|boxShadow|lineHeight)\s*:(?!\s*["'`]?\s*var\()/g,
  },
  {
    // THE RULE THAT KEEPS THIS SYSTEM FROM UNDOING ITSELF.
    //
    // MUI and emotion were removed wholesale, well before either design
    // system this product has had. The failure mode is not someone
    // deciding to bring MUI back wholesale — it is one import sneaking in
    // for one component the token layer does not happen to cover, and then
    // a second, until two design systems are live at once and neither can
    // be restyled. MATCH THE SPECIFIER, NOT THE `from` KEYWORD. Anchoring
    // on `from` caught `import X from "@mui/material"` and nothing else —
    // a review probe found three working ways past it:
    //
    //     import "@emotion/css";              // side-effect import
    //     require("@emotion/styled");         // CJS
    //     await import("@mui/icons-material") // dynamic
    //
    // all of which reintroduce a removed system with a green
    // tokens:verify. A quoted module specifier is the thing that is
    // actually forbidden, so that is what this looks for, in any syntax
    // that can carry one.
    id: "mui-emotion-import",
    category: "import-ban",
    name: "@mui or @emotion import (this product has no CSS-in-JS runtime)",
    appliesTo: "code",
    pattern: /["']@(?:mui|emotion)\/[^"']+["']/g,
  },
  {
    id: "brand-string",
    category: "value",
    name: 'literal brand string ("V1" / "AMG") outside lib/brand.ts',
    appliesTo: "code",
    pattern: /\b(V1|AMG)\b/g,
  },
  {
    // A REGRESSION FENCE, NOT A LIVE CONSTRAINT. @radix-ui/themes is
    // uninstalled — no file in the product imports it, so this rule
    // currently matches nothing, and that is the point: it stays in place
    // so an import cannot come back one component at a time inside a
    // screen that seems, on its own, like an easy place to reach for a
    // familiar library. No exemption, deliberately.
    //
    // MATCH THE SPECIFIER, NOT THE `from` KEYWORD — the @mui/@emotion rule
    // above already learned this lesson: anchoring on `from` misses
    // `import "@radix-ui/themes/styles.css"` (side-effect, no `from`),
    // `require("@radix-ui/themes")` (CJS), and `await import("@radix-ui/
    // themes")` (dynamic). All three are checked by the quoted specifier
    // instead, exactly like the @mui/@emotion rule.
    //
    // BACKTICKS COUNT. `import(`@radix-ui/themes`)` is legal and an early
    // version of this rule, which allowed only " and ', sailed straight
    // past it. That is precisely the "reads correct and is not" failure
    // the header records more than once, so the delimiter class carries `
    // too.
    id: "radix-themes-import",
    category: "import-ban",
    name: '"@radix-ui/themes" import (the package is uninstalled)',
    appliesTo: "code",
    pattern: /["'`]@radix-ui\/themes(?:\/[^"'`]*)?["'`]/g,
  },
  {
    // See the long note above SLOT_ORIGIN_FILE. Matches `var(--${x})` and
    // `var(${x})` in either quoting style, and — like every rule here —
    // runs against the whole file so a wrapped expression cannot hide.
    // The `[^)\n]*` stops at the closing paren so a legitimate
    // `var(--canvas)` followed later on the same line by an unrelated
    // template literal is not swept up.
    id: "runtime-css-var",
    category: "slot-origin",
    name: "CSS custom property assembled at runtime (only lib/theme-slots.ts may originate one)",
    appliesTo: "code",
    pattern: /var\(\s*(?:--)?[^)\n]*\$\{/g,
  },
  {
    // A JSX-expression value on one of the tenant theme attributes
    // (data-appearance / data-accent / data-density), or a spread that
    // could carry one. A literal (`data-appearance="dark"`) is untouched —
    // the rule is about a value the token layer did not choose, not about
    // the attributes themselves.
    id: "dynamic-theme-prop",
    category: "slot-origin",
    name: "tenant theme attribute (data-appearance/data-accent/data-density) set from a runtime value outside the app shell or the appearance preview",
    appliesTo: "code",
    pattern:
      /\bdata-(?:appearance|accent|density)\s*=\s*\{(?!["'`][^{}]*["'`]\s*\})/g,
  },
];

/*
 * ---------------------------------------------------------------------------
 * THE EXISTENCE RULE (category "existence").
 *
 * Everything above polices a value written where it should not be. It does
 * not catch the opposite failure: a reference to something that is spelled
 * correctly, looks like a token, and names NOTHING. `var(--gray-a5)` is not
 * a literal — it is the system's own vocabulary, one release out of date —
 * so no hex/color-function/named-color rule fires, it type-checks, it
 * builds, and it renders as no colour at all with no error anywhere. That
 * is how ~40 dead references shipped in an earlier design-system removal:
 * the nav rail's current-section marker, the skip link, the marketing
 * header's ground and hairline, the onboarding wizard's step circles, and
 * the accent picker's swatches all pointed at custom properties nothing
 * declared.
 *
 * The fix is not a new pattern to ban — it is a set of names to check
 * against, built once at start-up:
 *
 *   DECLARED_TOKEN_NAMES  every `--name` app/design/ledger.css and
 *                        app/globals.css declare, plus the `--font-schibsted`
 *                        name lib/fonts.ts's next/font loader creates (it
 *                        is never declared with a CSS `:` — the font loader
 *                        writes it).
 *
 * This is textual, like every rule above: a var() call built from a
 * template literal WITH interpolation is a DIFFERENT construction, already
 * caught (if written outside its one permitted home) by the
 * "runtime-css-var" slot-origin rule above — this existence check only
 * evaluates a fully-literal `var(--name)`.
 * ---------------------------------------------------------------------------
 */

function collectDeclaredTokenNames() {
  const names = new Set();
  const globalsCss = readFileSync(join(ROOT, "app", "globals.css"), "utf8");
  const ledgerCss = readFileSync(join(ROOT, "app", "design", "ledger.css"), "utf8");
  for (const css of [globalsCss, ledgerCss]) {
    for (const m of css.matchAll(/--([a-zA-Z][\w-]*)\s*:/g)) names.add(m[1]);
  }
  const fontsSrc = readFileSync(join(ROOT, "lib", "fonts.ts"), "utf8");
  for (const m of fontsSrc.matchAll(/variable:\s*"(--[a-zA-Z][\w-]*)"/g)) {
    names.add(m[1].slice(2));
  }
  return names;
}

const DECLARED_TOKEN_NAMES = collectDeclaredTokenNames();

function checkTokenExistence(file, content, relFile) {
  for (const m of content.matchAll(/var\(\s*(--[a-zA-Z][\w-]*)/g)) {
    const full = m[1];
    const name = full.slice(2);
    if (DECLARED_TOKEN_NAMES.has(name)) continue;
    violations.push({
      file: relFile,
      line: lineNumberAt(content, m.index),
      rule: "dead token reference (var(--…) names nothing ledger.css/globals.css declares)",
      snippet: full.replace(/\s+/g, " ").trim(),
    });
  }
}

/** @type {{file: string, line: number, rule: string, snippet: string}[]} */
const violations = [];

function walk(dir) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      if (entry === "node_modules" || entry === ".next") continue;
      walk(full);
    } else if (SCAN_EXTENSIONS.has(extname(full))) {
      scanFile(full);
    }
  }
}

function stripComments(content, ext) {
  let out = content.replace(/\/\*[\s\S]*?\*\//g, "");
  if (ext !== ".css") {
    out = out.replace(/(^|[^:])\/\/.*$/gm, "$1");
  }
  return out;
}

function lineNumberAt(content, index) {
  let line = 1;
  for (let i = 0; i < index; i++) {
    if (content[i] === "\n") line++;
  }
  return line;
}

function scanFile(file) {
  // isExempt() (EXEMPT_FILES) is consulted per-RULE below, not up front,
  // and only for category "value" rules. Short-circuiting the whole file
  // here — an early bug in this script — would silently exempt
  // app/globals.css, lib/brand.ts, lib/pdf-palette.ts and
  // lib/invoice-pdf.tsx from the import-ban rules too, with
  // lib/invoice-pdf.tsx (a real .tsx component file) the one place that
  // actually matters. It would also exempt every EXEMPT_FILES entry from
  // the existence rule, which must apply everywhere: a value-exempt file
  // spelling a value out on purpose is a different thing from that same
  // file referencing a token that does not exist.
  const fileIsValueExempt = isExempt(file);
  const ext = extname(file);
  const raw = readFileSync(file, "utf8");
  const content = stripComments(raw, ext);
  const kind = ext === ".css" ? "css" : "code";
  const relFile = relative(ROOT, file);

  for (const rule of RULES) {
    if (rule.appliesTo !== "both" && rule.appliesTo !== kind) continue;
    if (rule.category === "value" && fileIsValueExempt) continue;
    // The slot-origin carve-outs, keyed off `id` for the same reason the
    // one above is (see the note over RULES): an error message is prose
    // and is expected to change; behaviour must not move with it. These
    // are deliberately NOT folded into EXEMPT_FILES — that set means "may
    // spell a visual value out", and lib/theme-slots.ts specifically must
    // NOT be allowed to.
    if (rule.id === "runtime-css-var" && file === SLOT_ORIGIN_FILE) continue;
    if (
      rule.id === "dynamic-theme-prop" &&
      (file === SLOT_ORIGIN_FILE || THEME_APPLIER_FILES.has(file))
    ) {
      continue;
    }
    for (const match of content.matchAll(rule.pattern)) {
      if (rule.filter && !rule.filter(match)) continue;
      const line = lineNumberAt(content, match.index);
      // Show the actual matched text, not just the line it starts on —
      // for a multi-line match (e.g. a border-radius value wrapped onto
      // its own line) the starting line alone can be uninformative on
      // its own ("border-radius:" with no value visible).
      const snippetSource = match[0].replace(/\s+/g, " ").trim();
      violations.push({
        file: relFile,
        line,
        rule: rule.name,
        snippet:
          snippetSource.length > 160
            ? snippetSource.slice(0, 160) + "…"
            : snippetSource,
      });
    }
  }

  // THE EXISTENCE RULE. Never governed by EXEMPT_FILES (see the comment
  // above fileIsValueExempt). Runs on every scanned file, css or code —
  // var() appears in both plain stylesheets and inline JSX style objects.
  checkTokenExistence(file, content, relFile);
}

for (const dir of SCAN_DIRS) {
  const full = join(ROOT, dir);
  try {
    statSync(full);
    walk(full);
  } catch {
    // directory doesn't exist yet — nothing to scan
  }
}

if (violations.length > 0) {
  console.error(`\ntokens:verify FAILED — ${violations.length} violation(s):\n`);
  for (const v of violations) {
    console.error(`  ${v.file}:${v.line}  [${v.rule}]`);
    console.error(`    ${v.snippet}\n`);
  }
  console.error(
    "app/design/ledger.css owns every visual value in this product. Reach\n" +
      "for it instead of spelling a value out:\n\n" +
      "  colour, spacing, size    a Tailwind utility against a Ledger token —\n" +
      "                           bg-canvas, text-ink-2, rounded-card, gap-3.\n" +
      "                           components/ledger/ primitives already apply\n" +
      "                           the right ones; reach for those before a raw\n" +
      "                           className.\n" +
      "  something with no utility  style={{ ... var(--edge) ... }} is a legitimate\n" +
      "                           escape hatch. The scales are CSS custom\n" +
      "                           properties in app/design/ledger.css; use them\n" +
      "                           by NAME, and check that name is actually\n" +
      "                           declared there — a plausible-looking\n" +
      "                           var(--ledger-typo) that nothing declares\n" +
      "                           passes every rule above this one and renders\n" +
      "                           as nothing.\n" +
      "  the whole product's look  app/design/ledger.css, and nothing else.\n" +
      "                           There is no second place to override a value.\n\n" +
      `Only ${EXEMPT_FILES.size} files may spell a visual value out directly ` +
      "(see EXEMPT_FILES\nat the top of this script), and each documents why at the top of the file.\n\n" +
      "A per-tenant visual value (accent, density, light/dark) is a different rule:\n" +
      "  it must ORIGINATE in lib/theme-slots.ts, which enumerates every one of them\n" +
      "  and resolves an untrusted stored value against that list. A tenant theme\n" +
      "  attribute may only take a runtime value in the app shell\n" +
      "  (app/(app)/app-shell.tsx) and the appearance panel's preview; a var(--...)\n" +
      "  name may only be assembled at runtime in lib/theme-slots.ts. Add the slot\n" +
      "  to that file, don't inject the value here.\n"
  );
  process.exit(1);
}

console.log(
  `tokens:verify passed — no visual values hardcoded outside the ${EXEMPT_FILES.size} ` +
    `documented files, and every var() reference names something ` +
    `${join("app", "design", "ledger.css")} or ${join("app", "globals.css")} actually declares.`
);
