-- ===========================================================================
-- Two more things a Connect delivery can mean: a bank payment IN FLIGHT,
-- and one that FAILED.
--
-- Read 20260813100000_connect_auto_payments.sql first — this file changes
-- exactly one thing in it (the `outcome` vocabulary) and adds one index.
-- Nothing else about that table, its RLS, or its grants is touched, and no
-- other table in the schema is read or written by this file.
--
-- WHY A MIGRATION AT ALL, since the house rule is not to write one unless
-- the existing tables genuinely will not fit. Two cheaper options were
-- considered and both are worse:
--
--   REUSE 'needs_review'. That outcome means "real money arrived and this
--   product did not record it — a human must look", it is rendered as an
--   amber warning with a dismiss button, and it is what the invoice screen
--   nags about. An authorised ACH debit is none of those things: no money
--   has arrived, nothing is wrong, and there is nothing for the pilot to
--   do but wait. Dressing "your client paid, it lands Thursday" as a
--   warning is how a pilot learns to dismiss warnings.
--
--   REUSE 'ignored' AND INFER FROM invoice_id. It would work today —
--   'ignored' rows never carried an invoice_id before this change, so
--   `outcome = 'ignored' and invoice_id is not null` would in fact select
--   exactly the pending ones. It is a coincidence of the current code, not
--   a property of the data, and the column's own comment says 'ignored'
--   means "nothing to act on". A reader of the table would have no way to
--   tell a pending five-figure debit from an unrelated checkout on the
--   pilot's own Stripe account. Money-bearing states get names.
--
-- ADDITIVE, with one unavoidable exception that is not: a CHECK constraint
-- cannot be widened in place, so the outcome check is dropped and
-- re-created with two more allowed values. Every value that was legal
-- before is legal after — this can only ever accept more rows, never
-- reject one that already exists.
--
-- APPLY THIS BEFORE DEPLOYING THE BUILD THAT WRITES THE NEW OUTCOMES, and
-- that ordering is load-bearing rather than tidy. Being additive makes this
-- file safe to apply EARLY — against the previous build, which never writes
-- 'payment_pending' or 'payment_failed', it changes nothing observable — but
-- it does not make it safe to apply LATE. Code deployed first hits the OLD
-- check on every unsettled or failed ACH delivery: Postgres raises 23514,
-- the handler throws, the route answers 500, and Stripe retries the same
-- delivery for up to three days. Money is not at risk in that window (a card
-- payment and a SETTLED ACH payment both write outcomes the old check
-- already allows, so recording still works), but every bank debit in flight
-- is a 500 generator until this lands. docs/LAUNCH-GATES.md says the same
-- thing where the operator will meet it.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. outcome — two new values.
--
--    THE DROP IS DONE BY LOOKUP, NOT BY NAME, and that is worth the extra
--    six lines. 20260813100000 declares the check INLINE on the column, so
--    its name was generated by Postgres (`stripe_connect_events_outcome_
--    check`, by the tablename_colname_check convention). Hardcoding that
--    name means that if it is ever anything else — a hand-applied fix, a
--    restored dump, a future Postgres that names it differently — the
--    `drop ... if exists` silently does nothing, the ADD below succeeds,
--    and the table ends up with TWO checks where the older one still
--    refuses the two new values. The webhook would then 500 on every
--    pending ACH delivery, and the constraint that caused it would not be
--    named anywhere in this file. So: find every check on this table that
--    mentions `outcome`, drop those, add exactly one back. Re-runnable.
-- ---------------------------------------------------------------------------
do $$
declare
  con record;
begin
  for con in
    select conname
    from pg_constraint
    where conrelid = 'pilot.stripe_connect_events'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%outcome%'
  loop
    execute format(
      'alter table pilot.stripe_connect_events drop constraint %I', con.conname
    );
  end loop;
end $$;

alter table pilot.stripe_connect_events
  add constraint stripe_connect_events_outcome_allowed check (
    outcome is null or outcome in (
      -- Unchanged, and still the whole of what 20260813100000 allowed.
      'recorded',
      'duplicate',
      'needs_review',
      'refused',
      'ignored',
      -- NEW. An asynchronous payment (in practice ACH Direct Debit — it is
      -- the only delayed-notification method this product's links offer)
      -- has been AUTHORISED by the client and has not settled. No
      -- pilot.invoice_payments row exists, the invoice's balance is
      -- untouched, and its status has NOT moved to paid. Surfaced on the
      -- invoice screen as information, not as a warning, and superseded
      -- automatically (reviewed_at is stamped by the webhook) when the
      -- matching success or failure event lands for the same Checkout
      -- Session.
      'payment_pending',
      -- NEW. That debit FAILED — the client's bank did not complete it. No
      -- money ever existed, so there is nothing to reverse; what there IS
      -- to do is generate a new payment link, because the old one was
      -- consumed at mandate acceptance by the single-use restriction days
      -- before this event arrived. Surfaced, and dismissible, exactly like
      -- 'needs_review' and 'refused'.
      'payment_failed'
    )
  );

comment on column pilot.stripe_connect_events.outcome is
  'What the handler did: recorded | duplicate | needs_review | refused | ignored | payment_pending | payment_failed. FOUR are shown to the pilot on the invoice screen whenever the row resolved to one of their invoices: ''needs_review'' and ''refused'' (money arrived and this product did not record it — a human must look), ''payment_pending'' (a bank debit is authorised and settling; nothing to do, and it clears itself) and ''payment_failed'' (the debit failed; the spent link needs replacing). The rest are for the platform. ''payment_pending'' NEVER means money has arrived — see lib/stripe/connect-payments.ts.';

-- ---------------------------------------------------------------------------
-- 2. The invoice screen's index, for the two new outcomes.
--
--    A SECOND PARTIAL INDEX RATHER THAN A REPLACEMENT FOR
--    stripe_connect_events_needs_review_idx. Dropping and re-creating that
--    one over four values would be the tidier schema and the worse
--    migration: it is a live index behind a query on the invoice screen,
--    and this file has no reason to take it away and put it back. The
--    screen's query is `outcome in (four values) and reviewed_at is null`
--    for ONE invoice — a handful of rows either way — so the planner
--    picking one partial index, both, or neither is not a question worth a
--    schema risk.
-- ---------------------------------------------------------------------------
create index if not exists stripe_connect_events_async_idx
  on pilot.stripe_connect_events (account_id, invoice_id)
  where outcome in ('payment_pending', 'payment_failed') and reviewed_at is null;

-- The webhook's supersede write: "stamp the pending row for THIS Checkout
-- Session as reviewed, now that its outcome is known". Keyed the way that
-- write is keyed (connected account + session id), because object_id is
-- where the cs_... lands.
create index if not exists stripe_connect_events_object_idx
  on pilot.stripe_connect_events (connected_account_id, object_id)
  where object_id is not null;

-- ---------------------------------------------------------------------------
-- 3. No grant changes, and that is deliberate.
--
--    `reviewed_at` is already the one column `authenticated` may update
--    (20260813100000), and it is exactly the right authority for both new
--    outcomes: a pilot may dismiss a failed-payment prompt, and may dismiss
--    a pending notice they have read. Neither dismissal changes any money,
--    and neither can restate what Stripe sent. The webhook's service_role
--    client already holds full DML on this table, so the supersede write
--    needs nothing new either.
-- ---------------------------------------------------------------------------
